CREATE EXTERNAL TABLE events(event_time TIMESTAMP, url STRING, method STRING, browser STRING,email STRING,fname STRING,lname STRING,geoname STRING,	latitude FLOAT,	longitude FLOAT,sessionid STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' LOCATION '/user/ajjain/events';

CREATE EXTERNAL TABLE hourly_page_visits_by_users

CREATE EXTERNAL TABLE hourly_page_visits_by_geo

CREATE EXTERNAL TABLE hourly_refresh_back_hits

CREATE EXTERNAL TABLE hourly_product_view_by_users






